#!/usr/bin/with-contenv bash

# create files and directories
mkdir -p /config/aria2
touch \
	/config/aria2/aria2c.sess \
	/config/aria2/dht.dat

# permissions
chown -R abc:abc /config/aria2

# start aria2
s6-setuidgid abc /usr/bin/aria2c -c -D \
	--disable-ipv6=true \
	--enable-rpc \
	--rpc-allow-origin-all \
	--log=/config/aria2/aria2.log \
	--check-certificate=false \
	--save-session=/config/aria2/aria2c.sess \
	--input-file=/config/aria2/aria2c.sess \
	--dht-file-path=/config/aria2/dht.dat \
	--save-session-interval=2 \
	--continue=true \
	--rpc-save-upload-metadata=true \
	--force-save=true \
	--log-level=warn
